import { commonsFile, commonsImage, nasaFile, nasaImage, type AstronomyImageSource } from "@/lib/astronomy/image-sources";

export type SkyGalleryCategory = "机构深空" | "银河地景" | "行星月面" | "星座星野" | "天象事件" | "地球天空";

export interface SkyGalleryImage {
  id: string;
  title: string;
  category: SkyGalleryCategory;
  description: string;
  image: AstronomyImageSource;
  src: string;
  alt: string;
  objectSlug?: string;
  relatedObjectSlugs?: string[];
}

function item(
  id: string,
  title: string,
  category: SkyGalleryCategory,
  description: string,
  image: AstronomyImageSource,
  objectSlug?: string,
): SkyGalleryImage {
  return {
    id,
    title,
    category,
    description,
    image,
    src: commonsFile(image.file, 950),
    alt: title,
    objectSlug,
  };
}

function nasaItem(
  id: string,
  title: string,
  category: SkyGalleryCategory,
  description: string,
  nasaId: string,
  image: AstronomyImageSource,
  objectSlug?: string,
  size: "large" | "medium" | "small" = "large",
): SkyGalleryImage {
  return {
    id,
    title,
    category,
    description,
    image,
    src: nasaFile(nasaId, size),
    alt: title,
    objectSlug,
  };
}

function apodItem(
  id: string,
  title: string,
  description: string,
  date: string,
  imageUrl: string,
  location: string,
  objectSlug?: string,
): SkyGalleryImage {
  const sourceUrl = `https://apod.nasa.gov/apod/ap${date.replace(/-/g, "").slice(2)}.html`;
  const image = {
    file: imageUrl,
    sourceUrl,
    credit: "NASA APOD / 原作者见来源页",
    location,
    capturedAt: date,
    equipment: "地面天文摄影",
    license: "NASA APOD 来源页 / 原作者授权以来源页为准",
  } satisfies AstronomyImageSource;
  return {
    id,
    title,
    category: "地球天空",
    description,
    image,
    src: imageUrl,
    alt: title,
    objectSlug,
  };
}

const baseSkyGalleryImages: SkyGalleryImage[] = [
  nasaItem(
    "twilight-conjunction",
    "早霞中的木星与土星",
    "天象事件",
    "地面拍摄的晨昏行星合相，优先用于展示早霞中的真实天空和行星方位。",
    "NHQ202012130001",
    nasaImage("NHQ202012130001", {
      location: "Shenandoah National Park, USA",
      capturedAt: "2020-12-13",
      equipment: "Ground-based astrophotography",
    }),
    undefined,
    "small",
  ),
  nasaItem(
    "evening-planet-conjunction",
    "晚霞中的行星合相",
    "天象事件",
    "地面拍摄的晚霞与行星合相，优先用于展示地平线、余晖和天体之间的真实关系。",
    "NHQ202012210001",
    nasaImage("NHQ202012210001", {
      location: "Chapel Hill, North Carolina, USA",
      capturedAt: "2020-12-21",
      equipment: "Ground-based astrophotography",
    }),
    undefined,
    "small",
  ),
  nasaItem(
    "perseid-meteor-shower",
    "英仙座流星雨",
    "天象事件",
    "地面长曝光记录的流星雨，优先展示用户在地球上实际能看到的天象事件。",
    "NHQ202508030001",
    nasaImage("NHQ202508030001", {
      location: "Spruce Knob Mountain, West Virginia, USA",
      capturedAt: "2025-08-03",
      equipment: "30-second ground exposure",
    }),
    undefined,
    "small",
  ),
  nasaItem(
    "international-space-station",
    "国际空间站与地球夜空",
    "地球天空",
    "国际空间站视角下的地球大气辉光和夜间地表，保留人造卫星主题的独立展示。",
    "iss065e214537",
    nasaImage("iss065e214537", {
      location: "International Space Station",
      capturedAt: "2021-08-02",
      equipment: "International Space Station camera",
    }),
    undefined,
    "small",
  ),
  nasaItem(
    "earth-aurora",
    "地球极光与大气层",
    "地球天空",
    "从轨道观察地球极光和大气层结构，补充地面星空之外的地球天空影像。",
    "iss058e005282",
    nasaImage("iss058e005282", {
      location: "International Space Station",
      capturedAt: "2019-01",
      equipment: "International Space Station camera",
    }),
    undefined,
    "small",
  ),
  item(
    "milky-way-sagittarius",
    "银河与人马座方向",
    "银河地景",
    "宽视场银河摄影，适合建立真实夜空密度和银河带氛围的参考。",
    commonsImage("The Milky Way and Sagittarius Constellation (opo9930e).jpg", {
      credit: "Terrence Dickinson / ESA-Hubble",
      location: "Milky Way toward Sagittarius",
      capturedAt: "1999",
      equipment: "Wide-field astrophotography",
      license: "Public domain / see source page",
    }),
  ),
  item(
    "anji-starry-sky",
    "安吉星空",
    "银河地景",
    "国内夜空地景样张，用来补充本土观测场景的氛围参考。",
    commonsImage("Anji County Starry Sky.jpg", {
      credit: "Wikimedia Commons contributor",
      location: "Anji County, Zhejiang, China",
      capturedAt: "见来源页面",
      equipment: "Landscape astrophotography",
      license: "Wikimedia Commons / see source page",
    }),
  ),
  item(
    "orion-real-sky",
    "猎户座真实星野",
    "星座星野",
    "真实夜空中的猎户座，适合对照星座骨架和周围星点密度。",
    commonsImage("Orion - Clear night sky.jpg", {
      credit: "The359",
      location: "Eastern Pennsylvania, USA",
      capturedAt: "2007-11-08",
      equipment: "DSLR sky photograph",
      license: "Wikimedia Commons / CC BY-SA",
    }),
  ),
  item(
    "summer-triangle",
    "夏季大三角宽视场",
    "星座星野",
    "织女星、牛郎星、天津四所在区域的真实宽视场星野。",
    commonsImage("Wide-field view of the Summer Triangle.jpg", {
      credit: "A. Fujii / ESA-Hubble",
      location: "Summer Triangle sky field",
      capturedAt: "见来源页面",
      equipment: "Wide-field astrophotography",
      license: "ESA/Hubble source / see source page",
    }),
  ),
  item(
    "big-dipper",
    "北斗七星真实星野",
    "星座星野",
    "北斗区域的真实星野照片，用来对照明亮星组的视觉关系。",
    commonsImage("Big Dipper 20210116.jpg", {
      credit: "Wikimedia Commons contributor",
      location: "Northern sky field",
      capturedAt: "2021-01-16",
      equipment: "Night-sky photograph",
      license: "Wikimedia Commons / see source page",
    }),
  ),
  apodItem(
    "ground-orion-alps",
    "阿尔卑斯山上的猎户座",
    "猎户座从雪山和冰柱之间升起，地景比例清晰，能帮助用户把猎户座与真实地平线联系起来。",
    "2019-01-23",
    "https://apod.nasa.gov/apod/image/1901/OrionAlps_Vesely_960.jpg",
    "奥地利阿尔卑斯山",
    "orion",
  ),
  apodItem(
    "ground-taurus-meteors",
    "金牛座中的昴星团与流星",
    "真实地面长曝光同时记录金牛座、昴星团和流星，画面有明确的亮星组和动态主体。",
    "2019-01-07",
    "https://apod.nasa.gov/apod/image/1901/Geminids46P_jcc_1080.jpg",
    "金牛座方向的地面观测",
    "pleiades",
  ),
  apodItem(
    "ground-polaris-trails",
    "北极星周围的圆形星轨",
    "长曝光记录恒星围绕北极星旋转的轨迹，北方方向和北极星的固定感在画面中非常直观。",
    "2019-01-18",
    "https://apod.nasa.gov/apod/image/1901/Startrail_Funes1024.jpg",
    "特内里费岛天文台，加那利群岛",
    "polaris",
  ),
  apodItem(
    "ground-matterhorn-meteor",
    "马特洪峰、月亮与流星",
    "阿尔卑斯山剪影、月亮和流星被放在同一地平线中，展示夜空目标在真实场景里的视觉层次。",
    "2019-01-24",
    "https://apod.nasa.gov/apod/image/1901/cervin1300vetter.jpg",
    "瑞士马特洪峰",
    "moon",
  ),
  apodItem(
    "ground-winter-symphony",
    "北方冬夜的星空交响",
    "冰面前景、冬季亮星和极光共同构成画面，适合用于猎户座、天狼星所在冬季天空的视觉参照。",
    "2019-03-22",
    "https://apod.nasa.gov/apod/image/1903/HoughtonAurora_03_2019_600.jpg",
    "苏必利尔湖，北美",
    "sirius",
  ),
  apodItem(
    "ground-scorpius-spectacular",
    "天蝎座的地面星空",
    "天蝎座沿山脊铺开，心宿二所在区域在真实地景中有明确的方向和颜色层次。",
    "2019-04-07",
    "https://apod.nasa.gov/apod/image/1904/scorpio_guisard_960.jpg",
    "智利阿塔卡马沙漠",
    "antares",
  ),
  nasaItem(
    "ground-starry-kennedy-1",
    "海岸沙丘与银河",
    "地球天空",
    "海岸沙丘和银河形成强烈的明暗与纵深对比，保留地面观测的真实空间感。",
    "KSC-20191031-PH-GEB01_0003",
    nasaImage("KSC-20191031-PH-GEB01_0003", {
      credit: "NASA/Glenn Benson",
      location: "肯尼迪航天中心大西洋海岸，美国",
      capturedAt: "2019-10-31",
      equipment: "地面夜空摄影",
    }),
  ),
  nasaItem(
    "ground-sirius-rocket",
    "天狼星划过发射场上空",
    "地球天空",
    "地面长曝光把天狼星的星迹、发射塔和火箭组合在同一幅画面里，适合作为天狼星的现实观测参照。",
    "NHQ202203180015",
    nasaImage("NHQ202203180015", {
      credit: "NASA/Keegan Barber",
      location: "肯尼迪航天中心，美国佛罗里达",
      capturedAt: "2022-03-18",
      equipment: "30 分钟地面长曝光",
    }),
    "sirius",
    "large",
  ),
  nasaItem(
    "ground-antares-launch-pad",
    "心宿二、月亮与火箭",
    "地球天空",
    "月亮和心宿二出现在火箭上方，把一颗常见亮星放入极具辨识度的地面场景。",
    "NHQ202308240003",
    nasaImage("NHQ202308240003", {
      credit: "NASA/Joel Kowsky",
      location: "肯尼迪航天中心，美国佛罗里达",
      capturedAt: "2023-08-24",
      equipment: "地面夜空摄影",
    }),
    "antares",
    "large",
  ),
  nasaItem(
    "ground-canopus-earth",
    "老人星与地球夜景",
    "地球天空",
    "老人星在地球夜景上方出现，是少见的明亮南天恒星方向参照。",
    "iss006e28068",
    nasaImage("iss006e28068", {
      credit: "NASA/Donald R. Pettit",
      location: "国际空间站地球观测",
      capturedAt: "2003-02",
      equipment: "International Space Station camera",
    }),
    "canopus",
    "large",
  ),
  nasaItem(
    "star-vega-dust-disk",
    "织女星周围的尘埃盘",
    "机构深空",
    "斯皮策空间望远镜记录的织女星红外环境图像，把星图中的亮星连接到它真实的恒星系统。",
    "PIA07218",
    nasaImage("PIA07218", {
      credit: "NASA/JPL-Caltech",
      location: "织女星，天琴座",
      capturedAt: "2008",
      equipment: "Spitzer Space Telescope",
    }),
    "vega",
    "medium",
  ),
  nasaItem(
    "star-altair-surface",
    "牛郎星的快速自转",
    "机构深空",
    "高分辨率观测显示牛郎星因高速自转而变扁的恒星形状，适合补充星图中的牛郎星对象。",
    "PIA04204",
    nasaImage("PIA04204", {
      credit: "NASA/JPL",
      location: "牛郎星，天鹰座",
      capturedAt: "2006",
      equipment: "Palomar Testbed Interferometer",
    }),
    "altair",
    "medium",
  ),
  nasaItem(
    "star-betelgeuse-environment",
    "参宿四周围的恒星环境",
    "机构深空",
    "红超巨星参宿四周围的尘埃和气体结构，补充肉眼看到的橙红色亮星之外的对象细节。",
    "PIA16680",
    nasaImage("PIA16680", {
      credit: "NASA/ESA/Herschel/PACS/L. Decin et al.",
      location: "参宿四，猎户座",
      capturedAt: "2013",
      equipment: "Herschel Space Observatory",
    }),
    "betelgeuse",
    "medium",
  ),
  nasaItem(
    "star-fomalhaut-disk",
    "北落师门的尘埃环",
    "机构深空",
    "北落师门周围的尘埃盘是这颗南天亮星的重要特征，让星图对象不只停留在一个亮点。",
    "PIA04942",
    nasaImage("PIA04942", {
      credit: "NASA/JPL-Caltech",
      location: "北落师门，南鱼座",
      capturedAt: "2004",
      equipment: "Spitzer Space Telescope",
    }),
    "fomalhaut",
    "medium",
  ),
  nasaItem(
    "star-aldebaran-occultation",
    "毕宿五被土星环掩食",
    "机构深空",
    "卡西尼号记录毕宿五光线穿过土星环时的变化，把金牛座亮星与天体运动联系起来。",
    "PIA08287",
    nasaImage("PIA08287", {
      credit: "NASA/JPL/Space Science Institute",
      location: "毕宿五，金牛座",
      capturedAt: "2004",
      equipment: "Cassini spacecraft",
    }),
    "aldebaran",
    "medium",
  ),
  nasaItem(
    "star-rigel-occultation",
    "参宿七经过土星大气",
    "机构深空",
    "参宿七从土星大气边缘经过时的观测画面，补充猎户座中蓝白色亮星的对象资料。",
    "PIA08238",
    nasaImage("PIA08238", {
      credit: "NASA/JPL/Space Science Institute",
      location: "参宿七，猎户座",
      capturedAt: "2004",
      equipment: "Cassini spacecraft",
    }),
    "rigel",
    "medium",
  ),
  nasaItem(
    "star-orion-from-mars",
    "火星地平线上的猎户座亮星",
    "星座星野",
    "火星车从另一颗行星表面拍到的猎户座区域，其中包含参宿四和腰带三星，形成独特的对象对照。",
    "PIA05546",
    nasaImage("PIA05546", {
      credit: "NASA/JPL/Cornell",
      location: "火星表面，猎户座方向",
      capturedAt: "2004",
      equipment: "Mars Exploration Rover panoramic camera",
    }),
    "orion",
    "medium",
  ),
  nasaItem(
    "star-deneb-cygnus-region",
    "天津四所在的天鹅座区域",
    "星座星野",
    "WISE 拍摄的天鹅座恒星形成区域，连接星图中的天津四、天鹅座骨架和周围的星际云。",
    "PIA14102",
    nasaImage("PIA14102", {
      credit: "NASA/JPL-Caltech/UCLA",
      location: "天鹅座，天津四所在天区",
      capturedAt: "2011",
      equipment: "WISE space telescope",
    }),
    "deneb",
    "medium",
  ),
  nasaItem(
    "star-eta-carinae",
    "船底座 Eta Carinae",
    "机构深空",
    "Eta Carinae 的复杂喷发结构展示超巨星的剧烈演化，作为老人星所在南天区域的深空延伸。",
    "9906671",
    nasaImage("9906671", {
      credit: "NASA/CXC/SAO",
      location: "船底座 Eta Carinae",
      capturedAt: "1999",
      equipment: "Chandra X-ray Observatory",
    }),
    "medium",
  ),
  nasaItem(
    "star-vega-debris-ring",
    "织女星周围的行星残骸环",
    "机构深空",
    "织女星周围的尘埃和小天体环带，作为织女星详情页的第二个对象级图像。",
    "PIA16610",
    nasaImage("PIA16610", {
      credit: "NASA/JPL-Caltech",
      location: "织女星，天琴座",
      capturedAt: "2013",
      equipment: "Spitzer Space Telescope / artist concept",
    }),
    "vega",
    "medium",
  ),
  item(
    "orion-nebula",
    "猎户座大星云",
    "机构深空",
    "哈勃望远镜深空影像，展示星云本体结构和发光气体层次。",
    commonsImage("Orion Nebula - Hubble 2006 mosaic 18000.jpg", {
      credit: "NASA, ESA, M. Robberto (STScI/ESA), Hubble Space Telescope Orion Treasury Project Team",
      location: "Hubble Space Telescope observation",
      capturedAt: "2006",
      equipment: "Hubble Space Telescope",
      license: "NASA/ESA public outreach image / see source page",
    }),
    "orion-nebula",
  ),
  item(
    "andromeda",
    "仙女座星系",
    "机构深空",
    "星系整体摄影图，适合表现深空对象作为一个整体时的视觉价值。",
    commonsImage("Andromeda Galaxy (with h-alpha).jpg", {
      credit: "Adam Evans",
      location: "Deep-sky astrophotography",
      capturedAt: "见来源页面",
      equipment: "Telescope / astrophotography stack",
      license: "Wikimedia Commons / CC BY",
    }),
    "andromeda-galaxy",
  ),
  item(
    "pillars-of-creation",
    "创生之柱",
    "机构深空",
    "鹰状星云内的经典恒星形成区，适合展示专业机构深空摄影。",
    commonsImage("Pillars of creation 2014 HST WFC3-UVIS full-res denoised.jpg", {
      credit: "NASA, ESA/Hubble and the Hubble Heritage Team",
      location: "Hubble Space Telescope observation",
      capturedAt: "2014",
      equipment: "Hubble Space Telescope WFC3",
      license: "NASA/ESA public outreach image / see source page",
    }),
  ),
  item(
    "ngc-1300",
    "棒旋星系 NGC 1300",
    "机构深空",
    "哈勃拍摄的棒旋星系，补充星系结构类影像。",
    commonsImage("Hubble2005-01-barred-spiral-galaxy-NGC1300.jpg", {
      credit: "NASA, ESA, and The Hubble Heritage Team",
      location: "Hubble Space Telescope observation",
      capturedAt: "2005",
      equipment: "Hubble Space Telescope",
      license: "NASA/ESA public outreach image / see source page",
    }),
  ),
  item(
    "jupiter",
    "木星云带",
    "行星月面",
    "行星本体影像，展示肉眼亮点背后的真实圆面结构。",
    commonsImage("Jupiter by Cassini-Huygens.jpg", {
      credit: "NASA/JPL/Space Science Institute",
      location: "Cassini spacecraft observation",
      capturedAt: "2000-12",
      equipment: "Cassini spacecraft camera",
      license: "NASA public domain / see source page",
    }),
    "jupiter",
  ),
  item(
    "saturn",
    "土星与光环",
    "行星月面",
    "行星本体影像，展示需要望远镜或航天器才能分辨的光环结构。",
    commonsImage("Saturn during Equinox.jpg", {
      credit: "NASA/JPL/Space Science Institute",
      location: "Cassini spacecraft observation",
      capturedAt: "2009",
      equipment: "Cassini spacecraft camera",
      license: "NASA public domain / see source page",
    }),
    "saturn",
  ),
  nasaItem(
    "moon-and-earth-galileo",
    "地月同框",
    "行星月面",
    "伽利略号从深空回望地球与月球，作为月球详情页之外的地月系统视角。",
    "PIA00405",
    nasaImage("PIA00405", {
      location: "Galileo spacecraft observation",
      capturedAt: "1992-12-07",
      equipment: "Galileo spacecraft",
    }),
    "moon",
  ),
  nasaItem(
    "mars-rover-panorama",
    "火星地表全景",
    "行星月面",
    "火星车拍摄的地表全景，把火星详情页中的行星本体延伸到真实地表环境。",
    "PIA00782",
    nasaImage("PIA00782", {
      location: "Mars, photographed by a Mars Exploration Rover",
      capturedAt: "See NASA source page",
      equipment: "Mars Exploration Rover panoramic camera",
    }),
    "mars",
    "small",
  ),
  nasaItem(
    "venus-aphrodite-terra",
    "金星阿佛洛狄忒高地",
    "行星月面",
    "麦哲伦号雷达观测得到的金星地表区域，展示云层之下的真实地形主题。",
    "PIA00248",
    nasaImage("PIA00248", {
      location: "Venus, Magellan spacecraft radar observation",
      equipment: "Magellan spacecraft radar",
    }),
    "venus",
    "small",
  ),
  nasaItem(
    "crab-nebula-nasa",
    "蟹状星云",
    "机构深空",
    "专业机构拍摄的超新星遗迹，展示星云、脉冲星和深空结构的另一种尺度。",
    "PIA03606",
    nasaImage("PIA03606", {
      location: "Crab Nebula",
      equipment: "NASA space telescope observations",
    }),
    "crab-nebula",
  ),
  nasaItem(
    "helix-nebula",
    "螺旋星云",
    "机构深空",
    "斯皮策空间望远镜捕捉的行星状星云，补充与猎户座大星云不同的深空对象。",
    "PIA09178",
    nasaImage("PIA09178", {
      location: "Helix Nebula",
      equipment: "Spitzer Space Telescope",
    }),
  ),
  nasaItem(
    "m94-galaxy",
    "梅西耶94星系",
    "机构深空",
    "哈勃望远镜拍摄的星系结构，作为仙女座之外的另一个完整星系样本。",
    "PIA17011",
    nasaImage("PIA17011", {
      location: "Messier 94 galaxy",
      equipment: "Hubble Space Telescope",
    }),
  ),
  nasaItem(
    "earth-blue-marble",
    "地球蓝色弹珠",
    "行星月面",
    "从深空观察地球的代表性影像，连接地球详情页与太阳系尺度。",
    "PIA18033",
    nasaImage("PIA18033", {
      location: "Earth, observed from deep space",
      equipment: "NASA Earth-observing spacecraft",
    }),
    "earth",
  ),
  nasaItem(
    "triangulum-galaxy",
    "三角座星系 M33",
    "机构深空",
    "三角座星系的完整结构与恒星形成区域，同时连接对应对象详情页。",
    "PIA11969",
    nasaImage("PIA11969", { location: "Triangulum Galaxy (M33)", equipment: "NASA space telescope observations" }),
    "triangulum-galaxy",
  ),
  nasaItem(
    "whirlpool-galaxy",
    "涡状星系 M51",
    "机构深空",
    "M51 的旋臂与伴星系相互作用结构，同时连接对应对象详情页。",
    "PIA10200",
    nasaImage("PIA10200", { location: "Whirlpool Galaxy (M51)", equipment: "Hubble Space Telescope" }),
    "whirlpool-galaxy",
  ),
  nasaItem(
    "sombrero-galaxy",
    "草帽星系 M104",
    "机构深空",
    "M104 的横贯尘埃带与中央核球，同时连接对应对象详情页。",
    "0700064",
    nasaImage("0700064", { location: "Sombrero Galaxy (M104)", equipment: "Hubble Space Telescope" }),
    "sombrero-galaxy",
    "medium",
  ),
  nasaItem(
    "centaurus-a",
    "半人马座 A",
    "机构深空",
    "活动星系半人马座 A 的尘埃带和核心结构，同时连接对应对象详情页。",
    "PIA04624",
    nasaImage("PIA04624", { location: "Centaurus A galaxy", equipment: "NASA space telescope observations" }),
    "centaurus-a",
    "medium",
  ),
  nasaItem(
    "large-magellanic-cloud",
    "大麦哲伦云",
    "机构深空",
    "从轨道观察的大麦哲伦云，补充南天深空对象主题。",
    "iss071e418742",
    nasaImage("iss071e418742", { location: "Large Magellanic Cloud", equipment: "International Space Station camera" }),
    "large-magellanic-cloud",
  ),
  nasaItem(
    "small-magellanic-cloud",
    "小麦哲伦云",
    "机构深空",
    "小麦哲伦云的红外结构和星际尘埃，同时连接对应对象详情页。",
    "PIA25164",
    nasaImage("PIA25164", { location: "Small Magellanic Cloud", equipment: "Herschel, Planck, IRAS and COBE observations" }),
    "small-magellanic-cloud",
  ),
  nasaItem(
    "lagoon-nebula",
    "礁湖星云 M8",
    "机构深空",
    "人马座方向的发光气体云和恒星形成区，同时连接对应对象详情页。",
    "GSFC_20171208_Archive_e001955",
    nasaImage("GSFC_20171208_Archive_e001955", { location: "Lagoon Nebula (M8)", equipment: "Hubble Space Telescope" }),
    "lagoon-nebula",
  ),
  nasaItem(
    "ring-nebula",
    "环状星云 M57",
    "机构深空",
    "环状星云的环形气体结构，同时连接对应对象详情页。",
    "PIA14443",
    nasaImage("PIA14443", { location: "Ring Nebula (M57)", equipment: "NASA space telescope observations" }),
    "ring-nebula",
    "small",
  ),
  nasaItem(
    "dumbbell-nebula",
    "哑铃星云 M27",
    "机构深空",
    "哑铃星云的双叶轮廓，同时连接对应对象详情页。",
    "PIA04249",
    nasaImage("PIA04249", { location: "Dumbbell Nebula (M27)", equipment: "NASA space telescope observations" }),
    "dumbbell-nebula",
    "small",
  ),
  nasaItem(
    "pleiades",
    "昴星团 M45",
    "机构深空",
    "昴星团的恒星成员和星际尘埃，同时连接对应对象详情页。",
    "PIA14096",
    nasaImage("PIA14096", { location: "Pleiades star cluster (M45)", equipment: "NASA infrared space telescope observations" }),
    "pleiades",
  ),
  nasaItem(
    "hyades",
    "毕星团",
    "机构深空",
    "毕星团成员星与星团视场，同时连接对应对象详情页。",
    "GSFC_20171208_Archive_e001500",
    nasaImage("GSFC_20171208_Archive_e001500", { location: "Hyades star cluster", equipment: "Hubble Space Telescope" }),
    "hyades",
  ),
  nasaItem(
    "omega-centauri",
    "半人马座 Omega 星团",
    "机构深空",
    "半人马座 Omega 球状星团的密集恒星结构，同时连接对应对象详情页。",
    "PIA10372",
    nasaImage("PIA10372", { location: "Omega Centauri globular cluster", equipment: "NASA infrared space telescope observations" }),
    "omega-centauri",
    "medium",
  ),
];

const relatedObjectsByGalleryId: Record<string, string[]> = {
  "summer-triangle": ["vega", "altair", "deneb", "sadr"],
  "big-dipper": ["dubhe", "merak", "phecda", "megrez", "alioth", "mizar", "alkaid"],
  "orion-real-sky": ["betelgeuse", "rigel", "alnitak", "alnilam", "mintaka", "bellatrix", "saiph"],
  "ground-orion-alps": ["betelgeuse", "rigel", "alnitak", "alnilam", "mintaka", "bellatrix", "saiph"],
  "ground-taurus-meteors": ["pleiades", "aldebaran", "elnath"],
  "ground-polaris-trails": ["polaris", "kochab", "pherkad", "caph", "schedar"],
  "ground-winter-symphony": ["sirius", "procyon", "capella", "castor", "pollux", "aldebaran", "rigel"],
  "ground-scorpius-spectacular": ["antares", "shaula", "sargas", "dschubba", "acrab"],
  "milky-way-sagittarius": ["kaus-australis", "nunki", "ascella", "kaus-media", "kaus-borealis", "alnasl"],
  "hyades": ["aldebaran"],
  "star-deneb-cygnus-region": ["deneb", "sadr"],
  "star-orion-from-mars": ["betelgeuse", "rigel", "alnitak", "alnilam", "mintaka", "bellatrix", "saiph"],
  "andromeda": ["alpheratz", "mirach", "almach"],
  "ground-sicilian-alignment": ["spica", "regulus", "arcturus"],
};

export const skyGalleryImages: SkyGalleryImage[] = baseSkyGalleryImages.map((image) => ({
  ...image,
  relatedObjectSlugs: relatedObjectsByGalleryId[image.id],
}));
