name: Deploy To Windows Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on:
      - self-hosted
      - Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Deploy App
        shell: powershell
        run: .\scripts\deploy.ps1
